<?php
$z[0]=Array("global","",184,212);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",874,902);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("title","",1023,1038);
$z[3]=Array("info","",1439,1452);
$z[4]=Array("pubdate","",1895,1941);
$z[4][4]['function']="strftime(\"%Y\",@me)";
$z[5]=Array("pubdate","",2339,2385);
$z[5][4]['function']="strftime(\"%m\",@me)";
$z[6]=Array("pubdate","",2779,2825);
$z[6][4]['function']="strftime(\"%d\",@me)";
$z[7]=Array("global","",3124,3152);
$z[7][4]['name']="cfg_basehost";

?>