<?php
$z[0]=Array("arcurl","",185,200);
$z[1]=Array("title","",332,346);
$z[2]=Array("arcurl","",786,801);
$z[3]=Array("typename","",868,885);
$z[4]=Array("description","",1229,1279);
$z[4][4]['function']="cn_substr(@me,300)";
$z[5]=Array("pubdate","",1664,1710);
$z[5][4]['function']="strftime(\"%Y\",@me)";
$z[6]=Array("pubdate","",2108,2154);
$z[6][4]['function']="strftime(\"%m\",@me)";
$z[7]=Array("pubdate","",2622,2668);
$z[7][4]['function']="strftime(\"%d\",@me)";

?>