<div class="xn_c_index_75_cItems">
                                                    <div class="xn_c_index_75_cImg">
                                                        <a href="[field:arcurl/]">
                                                            <img data-original="/Private/NewsImgs/3127969c1400cb9daa76.jpg" alt="[field:title/]" src="{dede:global.cfg_templets_skin/}/images/3127969c1400cb9daa76.jpg">
                                                        </a>
                                                    </div>
                                                    <div class="xn_c_index_75_cCont">
                                                        <div class="xn_c_index_75_cTitle">
                                                            <a href="[field:arcurl/]">
                                                                [field:typename/]
                                                            </a>
                                                        </div>
                                                        <div class="xn_c_index_75_cContent">
                                                            <span id="xn_c_index_75_cData2_ctl01_xn_c_index_75_cContent2">[field:description function="cn_substr(@me,300)"/]...</span>
                                                        </div>
                                                        <div class="xn_c_index_75_cDateTime">
                                                            <span class="xn_c_index_75_year2">
                                                                <span id="xn_c_index_75_cData2_ctl01_xn_c_index_75_year2">[field:pubdate function='strftime("%Y",@me)'/]</span>
                                                            </span>
                                                            <span class="xn_c_index_75_line3">/</span>
                                                            <span class="xn_c_index_75_month2">
                                                                <span id="xn_c_index_75_cData2_ctl01_xn_c_index_75_month2">[field:pubdate function='strftime("%m",@me)'/]</span>
                                                            </span>
                                                            <span class="xn_c_index_75_line4">/</span>
                                                            <span class="xn_c_index_75_day2">
                                                                <span id="xn_c_index_75_cData2_ctl01_xn_c_index_75_day2">27</span>
                                                                [field:pubdate function='strftime("%d",@me)'/]
                                                            </span>
                                                        </div>
                                                        <div class="xn_c_index_75_cView2">
                                                            <a href="{dede:global.cfg_basehost/}/news_view.aspx?TypeId=133&amp;Id=442&amp;Fid=t2:133:2">查看详情&gt;&gt;</a>
                                                        </div>
                                                    </div>
                                                </div>