<div class="xn_c_news_18_xhcoentbox">
                                            <div class="xn_c_news_18_lftbox">
                                                <a title="" href="[field:arcurl/]" target="_blank"></a>
                                            </div>
                                            <div class="xn_c_news_18_ritbox">
                                                <div class="xn_c_news_18_title">
                                                    <a title="" href="[field:arcurl/]" target="_blank">
                                                        [field:title /]
                                                    </a>
                                                </div>
                                                <div class="xn_c_news_18_timebox">
                                                    <span class="xn_c_news_18_newsYear"> 
                                                        <span id="xn_c_news_18_Data_ctl01_xn_c_news_18_newsYear">
                                                            [field:pubdate function='strftime("%Y",@me)'/]
                                                        </span>
                                                    </span> 
                                                    <span class="xn_c_news_18_newsLine1">-</span> 
                                                    <span class="xn_c_news_18_newsMonth"> 
                                                        <span id="xn_c_news_18_Data_ctl01_xn_c_news_18_newsMonth">
                                                            [field:pubdate function='strftime("%m",@me)'/]
                                                        </span>
                                                        </span> 
                                                    <span class="xn_c_news_18_newsLine2">-</span> 
                                                    <span class="xn_c_news_18_newsDay"> 
                                                        <span id="xn_c_news_18_Data_ctl01_xn_c_news_18_newsDay">
                                                            [field:pubdate function='strftime("%d",@me)'/]
                                                        </span>
                                                    </span> 
                                                </div>
                                                <div class="xn_c_news_18_coent">
                                                    [field:description function="cn_substr(@me,300)"/]…
                                                </div>
                                            </div>
                                        </div>