<?php
$z[0]=Array("global","",184,212);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",874,902);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("title","",1023,1038);
$z[3]=Array("pubdate","",1882,1928);
$z[3][4]['function']="strftime(\"%Y\",@me)";
$z[4]=Array("pubdate","",2326,2372);
$z[4][4]['function']="strftime(\"%m\",@me)";
$z[5]=Array("pubdate","",2766,2812);
$z[5][4]['function']="strftime(\"%m\",@me)";
$z[6]=Array("global","",3111,3139);
$z[6][4]['name']="cfg_basehost";

?>