<?php
$z[0]=Array("arcurl","",234,249);
$z[1]=Array("title","",402,416);
$z[2]=Array("title","",425,439);
$z[3]=Array("arcurl","",946,961);
$z[4]=Array("title","",1020,1034);
$z[5]=Array("click","",1717,1731);
$z[6]=Array("pubdate","",2453,2499);
$z[6][4]['function']="strftime(\"%Y\",@me)";
$z[7]=Array("pubdate","",2877,2923);
$z[7][4]['function']="strftime(\"%m\",@me)";
$z[8]=Array("pubdate","",3337,3383);
$z[8][4]['function']="strftime(\"%d\",@me)";
$z[9]=Array("writer","",3609,3624);
$z[10]=Array("source","",3658,3673);
$z[11]=Array("arcurl","",5620,5635);

?>