<div class="xn_c_index_75_cItems">
                                                    <div class="xn_c_index_75_cImg">
                                                        <a href="[field:arcurl/]">
                                                            <img data-original="/Private/NewsImgs/284610f444bdc739e30c.jpg" alt="[field:title/]" src="{dede:global.cfg_templets_skin/}/images/284610f444bdc739e30c.jpg">
                                                        </a>
                                                    </div>
                                                    <div class="xn_c_index_75_cCont">
                                                        <div class="xn_c_index_75_cTitle">
                                                            <a href="[field:arcurl/]">
                                                                [field:title/]
                                                            </a>
                                                        </div>
                                                        <div class="xn_c_index_75_cContent">
                                                            <span id="xn_c_index_75_cData2_ctl00_xn_c_index_75_cContent2">[field:description function="cn_substr(@me,300)"/]...</span>
                                                        </div>
                                                        <div class="xn_c_index_75_cDateTime">
                                                            <span class="xn_c_index_75_year2">
                                                                <span id="xn_c_index_75_cData2_ctl00_xn_c_index_75_year2">2018</span>
                                                            </span>
                                                            <span class="xn_c_index_75_line3">/</span>
                                                            <span class="xn_c_index_75_month2">
                                                                <span id="xn_c_index_75_cData2_ctl00_xn_c_index_75_month2">12</span>
                                                            </span>
                                                            <span class="xn_c_index_75_line4">/</span>
                                                            <span class="xn_c_index_75_day2">
                                                                <span id="xn_c_index_75_cData2_ctl00_xn_c_index_75_day2">28</span>
                                                            </span>
                                                        </div>
                                                       <!--  <div class="xn_c_index_75_cView2">
                                                            <a href="{dede:global.cfg_basehost/}/news_view.aspx?TypeId=133&amp;Id=443&amp;Fid=t2:133:2">查看详情&gt;&gt;</a>
                                                        </div> -->
                                                    </div>
                                                </div>