<li class="clearfix">
                          
                            <div class="imgW">
                             < a href=" "> [field:image/]</ a>
                            </div>
                            <div class="txtW">
                              < a href="[field:arcurl/]">
                                <strong class="listTit">[field:title/]</strong>
                                <p class="txtT01">
                                    <span class="date"> 2019-07-16</span>
                                </p >
                                </ a><p class="txtT02">< a href="[field:arcurl/]">
                                  <!--  -->
                                  </ a>< a href="[field:arcurl/]" target="_blank"> [field:description function='cn_substr(@me,80)'/]...</ a>
                                </p >
                                
                            </div>
                        </li>