<div class="xn_ba_js_1_element" frameindex="1" id="ea_ba_no_b_0" style="opacity: 1; left: -2117.9px;">
                    <div class="xn_ba_js_1_bigImg">
                        <a name="1" href="[field:title/]" target="_blank">
                            <img alt="[field:shorttitle/]" rel="b" data-original="../../../TempUpload/20180530135914414.jpg" src="[field:image/]">
                        </a>
                    </div>
                </div>