<div id="xn_c_index_130_Data_ctl00_xn_c_index_130_Style" class="xn_c_index_130_faqbox1">
                                        <div class="xn_c_index_130_faqimg">
                                            <a target="_blank" href="[field:arcurl/]">
                                                <img data-original="https://1.rc.xiniu.com/td/Private/NewsImgs/6355103933873437502004606561.jpg" alt="[field:title/]" title="[field:title/]" src="{dede:global.cfg_templets_skin/}/images/6355103933873437502004606561.jpg">
                                            </a>
                                        </div>
                                        <div class="xn_c_index_130_faqContent">
                                            <div class="xn_c_index_130_faqTitle">
                                                <span class="xn_c_index_130_faqTitle_t1">
                                                    <a target="_blank" href="[field:arcurl/]">
                                                        [field:title/]
                                                    </a>
                                                </span>
                                            </div>
                                            <div class="xn_c_index_130_faqNum">
                                                <span class="xn_c_index_130_faqNumwz">
                                                
                                                <span name="_xn_c_index_130_faqNum_t1">浏览次数：</span>
                                                
                                                </span>
                                                <span class="xn_c_index_130_faqNum_t2">[field:click/]</span>
                                            </div>
                                            <div class="xn_c_index_130_indDate">
                                                    <span class="xn_c_index_130_jobDate">
                                                    
                                                        <span name="_xn_c_index_130_jobDate">发布时间：</span>
                                                    
                                                    </span>
                                                    <span class="xn_c_index_130_indYear">
                                                        <span id="xn_c_index_130_Data_ctl00_xn_c_index_130_indYearText">2015</span>
                                                    </span>
                                                    <span class="xn_c_index_130_indLine">-</span>
                                                    <span class="xn_c_index_130_indMonth">
                                                        <span id="xn_c_index_130_Data_ctl00_xn_c_index_130_indMonthText">04</span>
                                                    </span>
                                                    <span class="xn_c_index_130_indLine">-</span>
                                                    <span class="xn_c_index_130_indDay">                                        
                                                        <span id="xn_c_index_130_Data_ctl00_xn_c_index_130_indDayText">02</span>
                                                    </span>
                                            </div>
                                            <div class="xn_c_index_130_faqContext" ej="edit_span">作者：[field:writer/] &nbsp;&nbsp;&nbsp;信息来源：[field:source/]<!-- <br><br><br>上午，为期两天的第六届北京全球友好机场总裁论坛召开。记者获悉，为提升航班正常性，目前，首都机场东区新增5个停机位即将投入使用，年内将陆续增加23个停机位；T3航站楼国内23条安检通道的改造已经完成，国际安检通道扩容改造预计10月底可以完成。&nbsp;　　首都机场相关负责人表示，国内大型枢纽机场特别是首都机场航班正常率不高，主要有三个方面的深层次原因：&nbsp;　　一是空域资源十分紧张。根据民航局发布的最新数据，2017年7月全国航班正常率为50.76%，天气原因占延误航班的58.6%；空域活动原因占延误航班的26%。当前，国家正在大力推进空域改革，希望在不久的将来，中国民用空域资源紧张的局面能够得到有效缓解。&nbsp;　　二是时刻资源过度利用。2017年首都机场高峰时段最高起降达到了103架次，远超时刻容量标准的86架次。超容运行带来的就是运行冗余度降低，特殊天气或者突发情况的应对能力不足，导致大面积和长时间延误的可能性大幅增加。&nbsp;　　三是地面资源亟待补充。国内大型机场普遍存在“规划跟不上变化、设计赶不上实际”的问题，首都机场2016年旅客吞吐量达9439万人次，超过现有规划设计容量8200万人次约15%，实际起降达到60.6万架次，超设计容量50万架次约20%。超负荷运行带来的主要后遗症，就是基础设施和地面资源的改造和补充，难以跟上发展步伐，难以满足实际需求。尤其是停机位、跑滑系统、安检通道、保障车辆等关键资源的不足，严重制约着首都机场的运行效率提升。 --></div>
                                            <div class="xn_c_index_130_faqMore">
                                                <a target="_blank" href="[field:arcurl/]">
                                                
                                                    <span name="_xn_c_index_130_faqMore">更多详情&gt;&gt;</span>
                                                
                                                </a>
                                            </div>
                                        </div>
                                        <div class="clear"></div>
                                    </div>