<?php
$z[0]=Array("global","",184,212);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",874,902);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("title","",1023,1038);
$z[3]=Array("description","",1439,1489);
$z[3][4]['function']="cn_substr(@me,300)";
$z[4]=Array("pubdate","",1932,1978);
$z[4][4]['function']="strftime(\"%Y\",@me)";
$z[5]=Array("pubdate","",2376,2422);
$z[5][4]['function']="strftime(\"%m\",@me)";
$z[6]=Array("pubdate","",2816,2862);
$z[6][4]['function']="strftime(\"%m\",@me)";
$z[7]=Array("global","",3161,3189);
$z[7][4]['name']="cfg_basehost";

?>