<div class="xn_c_index_75_cont">
                                     
                                    <div class="xn_c_index_75_cwrap" style="display: block;">
                                        
                                                <div class="xn_c_index_75_cItems">
                                                    <div class="xn_c_index_75_cImg">
                                                        <a href="{dede:global.cfg_basehost