
        <li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>
                                            
                                                <li id="xn_n_13_navli3">
                                                    <div><a href="http://www.szair-edu.com/products.aspx?TypeId=28&amp;FId=t3:28:3" target="_self">培训课程</a></div>
                                                </li>
                                            
                                                <li id="xn_n_13_navli4">
                                                    <div><a href="http://www.szair-edu.com/case_complex.aspx?FId=n4:4:4" target="_self">招聘信息</a></div>
                                                </li>
                                            
                                                <li id="xn_n_13_navli27">
                                                    <div><a href="http://www.szair-edu.com/enrollment_complex.aspx?FId=n27:27:27" target="_self">学员风采</a></div>
                                                </li>
                                            
                                                <li id="xn_n_13_navli1">
                                                    <div><a href="http://www.szair-edu.com/about_complex.aspx?FId=n1:1:1" target="_self" rel="nofollow">关于我们</a></div>
                                                </li>
                                            
                                                <li id="xn_n_13_navli26">
                                                    <div><a href="http://www.szair-edu.com/teachers_complex.aspx?FId=n26:26:26" target="_self" rel="nofollow">名师团队</a></div>
                                                </li>
                                            
                                                <li id="xn_n_13_navli11">
                                                    <div><a href="http://www.szair-edu.com/job_online.aspx?FId=n11:11:11" target="_self" rel="nofollow">在线测评</a></div>
                                                </li>
                                            
                                                <li id="xn_n_13_navli7">
                                                    <div><a href="http://www.szair-edu.com/contact.aspx?FId=n7:7:7" target="_self" rel="nofollow">联系我们</a></div>
                                                </li>
                                            
                                    </ul>
                                </div>
                            </div>
                            
                        </div>
                           <script>
  					  $(function(){
    					$('#xn_n_13_navli1 a').attr("rel", "nofollow");
						$('#xn_n_13_navli26 a').attr("rel", "nofollow");
						$('#xn_n_13_navli11 a').attr("rel", "nofollow");
						$('#xn_n_13_navli7 a').attr("rel", "nofollow");
						
  						  });
 						 </script>

                        
                    </div>
                    
                </div>
                
                
                    <div id="t_tel" class="t_tel">
                        <span class="t_tel_ts"><span name="_t_tel1|">咨询热线</span></span>
                        <span class="t_tel_nb"><span name="_t_tel2|">010-64568575</span></span>
                        
                    </div>
                
                </div>
            </div>
             
        </div>
        
        <div id="ea_ba">

  <div class="xn_ba_js_1_banner" id="xn_ba_js_1_banner" style="visibility: visible;"> 
    
    <div class="xn_ba_js_1_element" frameindex="1" id="ea_ba_no_b_0" style="opacity: 1; left: -2117.9px;">
      <div class="xn_ba_js_1_bigImg"><a name="1" href="http://www.szair-edu.com/pro.aspx?FId=n3:3:3" target="_blank"><img alt="空姐培训学校" rel="b" data-original="../../../TempUpload/20180530135914414.jpg" src="{dede:global.cfg_templets_skin