<div class="xn_c_news_18_xhcoentbox">
                                            <div class="xn_c_news_18_lftbox">
                                                <a title="" href="[field:arcurl/]" target="_blank">
                                                    <img data-original="/Private/NewsImgs/3127969c1400cb9daa76.jpg" alt="" title="" src="{dede:global.cfg_templets_skin/}/images/3127969c1400cb9daa76.jpg">
                                                </a>
                                            </div>
                                            <div class="xn_c_news_18_ritbox">
                                                <div class="xn_c_news_18_title">
                                                    <a title="" href="[field:arcurl/]" target="_blank">
                                                        
                                                    </a>
                                                </div>
                                                <div class="xn_c_news_18_author">
                                                    <span class="xn_c_news_18_author1">
                                                        
                                                        <span name="_news_18_author1">
                                                            作者：
                                                        </span>
                                                        
                                                    </span>
                                                    <span class="xn_c_news_18_author2">
                                                        
                                                    </span>
                                                </div>
                                                <div class="xn_c_news_18_timebox">
                                                    <span class="xn_c_news_18_timewz">
                                                        
                                                        <span name="_news_18_timewz">
                                                            发布时间：
                                                        </span>
                                                        
                                                    </span>
                                                    <span class="xn_c_news_18_newsYear"> 
                                                        <span id="xn_c_news_18_Data_ctl01_xn_c_news_18_newsYear">
                                                            [field:pubdate function='strftime("%Y",@me)'/]
                                                        </span>
                                                    </span> 
                                                    <span class="xn_c_news_18_newsLine1">-</span> 
                                                    <span class="xn_c_news_18_newsMonth"> 
                                                        <span id="xn_c_news_18_Data_ctl01_xn_c_news_18_newsMonth">
                                                            [field:pubdate function='strftime("%m",@me)'/]
                                                        </span>
                                                        </span> 
                                                    <span class="xn_c_news_18_newsLine2">-</span> 
                                                    <span class="xn_c_news_18_newsDay"> 
                                                        <span id="xn_c_news_18_Data_ctl01_xn_c_news_18_newsDay">
                                                            [field:pubdate function='strftime("%d",@me)'/]
                                                        </span>
                                                    </span> 
                                                </div>
                                                <div class="xn_c_news_18_click">
                                                    <span class="xn_c_news_18_click1">
                                                        
                                                        <span name="_news_18_click1">
                                                            点击次数：
                                                        </span>
                                                        
                                                    </span>
                                                    <span class="xn_c_news_18_click2">
                                                        85
                                                    </span>
                                                </div>
                                                <div class="xn_c_news_18_coent" ej="edit_span"></div>
                                                <div class="xn_c_news_18_more">
                                                    <a title="" href="[field:arcurl/]" target="_blank">
                                                        
                                                        <span name="_news_18_more">查看更多&gt;&gt;</span>
                                                        
                                                    </a>
                                                </div>
                                            </div>
                                        </div>