<?php
$z[0]=Array("global","",184,212);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",874,902);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("title","",1023,1038);
$z[3]=Array("infos","",1443,1457);
$z[4]=Array("pubdate","",1900,1946);
$z[4][4]['function']="strftime(\"%Y\",@me)";
$z[5]=Array("pubdate","",2344,2390);
$z[5][4]['function']="strftime(\"%m\",@me)";
$z[6]=Array("pubdate","",2784,2830);
$z[6][4]['function']="strftime(\"%m\",@me)";
$z[7]=Array("global","",3129,3157);
$z[7][4]['name']="cfg_basehost";

?>