 
                                    <li class="[field:global name=autoindex runphp="yes"](@me==2)? @me="xn_c_index_75_colLi xn_c_index_75_colLiCurr":@me="xn_c_index_75_colLi";[/field:global]">
                                        <span id="xn_c_index_75_colName[field:global runphp='yes' name=autoindex]@me=@me+1;[/field:global]">行业动态</span>
                                    </li>
                                