<?php
$z[0]=Array("channel"," \n                                    <li class=\"xn_c_index_75_colLi xn_c_index_75_colLiCurr\">\n                                        <span id=\"xn_c_index_75_colName2\">[field:title/]</span>\n                                    </li>\n                                 <!--  <li class=\"xn_c_index_75_colLi\">\n                                        <span id=\"xn_c_index_75_colName3\">[field:title/]</span>\n                                    </li> -->\n                                  <!-- <li class=\"xn_c_index_75_colLi\">\n                                        <span id=\"xn_c_index_75_colName4\">[field:title/]</span>\n                                    </li> -->\n                                </ul>\n                               ",166,945);
$z[0][4]['row']="10";
$z[0][4]['type']="son";
$z[1]=Array("global","",1585,1617);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",3992,4019);
$z[2][4]['name']="cfg_basehost";

?>