<div class="xn_c_index_75_wrap" id="xn_c_index_75_wrap">
                            
                            <div class="xn_c_index_75_main">
                                <ul class="xn_c_index_75_colUl">                                
                                    
                                    <li class="xn_c_index_75_colLi xn_c_index_75_colLiCurr">
                                        <span id="xn_c_index_75_colName2">[field:title/]</span>
                                    </li>
                                  <li class="xn_c_index_75_colLi">
                                        <span id="xn_c_index_75_colName3">[field:title/]</span>
                                    </li>
                                  <li class="xn_c_index_75_colLi">
                                        <span id="xn_c_index_75_colName4">[field:title/]</span>
                                    </li>
                                </ul>
                            
                                <div class="xn_c_index_75_cont">
                                     
                                    <!-- <div class="xn_c_index_75_cwrap" style="display: block;">
                                        
                                                <div class="xn_c_index_75_cItems">
                                                    <div class="xn_c_index_75_cImg">
                                                        <a href="{dede:global.cfg_basehost