<?php
$z[0]=Array("arcurl","",182,197);
$z[1]=Array("arcurl","",500,515);
$z[2]=Array("title","",590,605);
$z[3]=Array("pubdate","",1065,1111);
$z[3][4]['function']="strftime(\"%Y\",@me)";
$z[4]=Array("pubdate","",1602,1648);
$z[4][4]['function']="strftime(\"%m\",@me)";
$z[5]=Array("pubdate","",2139,2185);
$z[5][4]['function']="strftime(\"%d\",@me)";
$z[6]=Array("description","",2514,2564);
$z[6][4]['function']="cn_substr(@me,300)";

?>