<?php
$z[0]=Array("global","",238,265);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",398,430);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",1228,1255);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("channel","\r\n                              <li>\r\n                                 <a href=\"[field:typeurl /]\">[field:typename /]</a>\r\n                               </li>\r\n                            ",1588,1817);
$z[3][4]['type']="top";

?>